apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
spec:
  selector:
    matchLabels:
      app: backend2
  replicas: 1
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend2
        image: ravianxreaver/go_service2:v2
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 10002